### ISSUE TITLE
Syntax change for makeParallel & makeSeries?

### ISSUE THREAD

**Issue by godspeedelbow** [whyhankee/flw#1]
I was thinking about `flw.makeParallel`, I like the idea! In `async` you often end up with anonymous functions or using `_.partial` or the like. 

However, I think it would be syntactically more beautiful to use `flw.make.parallel`. In this way, you only have to once explain the functionality of adding `make` in between, instead of writing duplicate documentation for both the normal and the make-version of each function (now you have only two, but I can imagine that there's probably about 10 different control flows, `flw` could contain - looking at `async`).

**Comment by godspeedelbow** [comment]
I can create a PR if you like the idea :)

**Comment by whyhankee** [comment]
You are right, make.* is a lot nicer than makeSerial & makeParallel.
PR would be really nice, thanks!
