### ISSUE TITLE
Add ES6 Map support to setup a waterfall flow

### ISSUE THREAD

**Issue by godspeedelbow** [whyhankee/flw#2]
It's impossible to use an Object to setup a waterfall flow, because the order of the keys is not guaranteed on an Object. However, an ES6 Map is ordered! (["A Map object iterates its elements in insertion order"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)). Without an Map literal, Map will be unwieldy, [but there's hope](https://esdiscuss.org/topic/map-literal), but assuming that gets fixed, it could look something like this:

```
flw.waterfall([ //imaginary Map literal syntax
  foo: function getFoo(callback) {
    callback(null, 'I pity the foo');
  },
  bar: function getBar(results, callback) {
    console.log(results.foo);
    callback();
  },
]);
```

`getBar` gets two arguments, `results` and `callback`. `results` is a hashmap containing keys for each of the previously finished functions, in this case one key `foo` which contains the value with which the `getFoo` callback was called.

**Comment by whyhankee** [comment]
A waterfall is just a `series` that returns values. Now you have a nice context object so a waterfall is not really needed I think ..

**Comment by godspeedelbow** [comment]
I think this would be a whole new project, `mapperFall` or something :)
