### ISSUE TITLE
Bring function signature in line between .parallel and .make.parallel

### ISSUE THREAD

**Issue by godspeedelbow** [whyhankee/flw#4]
I think it's ambiguous that `.parallel` takes an Array of functions and `.make.parallel` doesn't use an Array, but just uses the arguments. This is bound to lead to confusion: both should be an Array. 

Then we can allow the user to provide a done function to `make.parallel`. 

So, new syntax:

    flw.series([
      flw.make.parallel([a, b], onParallelDone),
      flw.make.series([c, d, e], onSeriesDone),
    ], onDone);

**Comment by whyhankee** [comment]
You are right, this was overdue.
